version: '3.5'
services:
  server:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: server
    volumes:
      - ../storage/:/app/storage/
      - ../../snapshots/:/app/snapshots/
    ports:
      - 5000:5000
    command: uvicorn app.main:app --host 0.0.0.0 --port 5000
    depends_on:
      - redis

  worker01:
    build:
      context: ../
      dockerfile: docker/worker.dockerfile
    container_name: worker01
    volumes:
      - ../storage/:/app/storage/
      - ../../snapshots/:/app/snapshots/
    depends_on:
      - server
      - redis
  # worker02:
  #   build:
  #     context: .
  #     dockerfile: worker.dockerfile
  #   container_name: worker02
  #   volumes:
  #     - ./storage/:/app/storage/
  #   #command:
  #   #  - rq worker --url redis://redis:6379 queue2
  #   depends_on:
  #     - server
  #     - redis
  
  redis:
    image: redis:4.0.6-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data